# GitHub Actions Workflow to deploy the Album Management UI to GitHub Pages
# This workflow securely injects the Firebase config into the HTML file before deployment.

name: Deploy Album Management UI to GitHub Pages

on:
  # Runs on pushes to the main branch
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Inject Firebase Config
        # This step uses a small Node.js script to perform the replacement.
        # It's more robust than using 'sed' because it avoids shell expansion issues
        # with special characters in the secret JSON.
        env:
          # Pass the secret into an environment variable for the script to use
          FIREBASE_CONFIG_JSON: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          node -e "
            const fs = require('fs');
            const path = './docs/album-manager/index.html';
            let content = fs.readFileSync(path, 'utf8');
            
            const config = process.env.FIREBASE_CONFIG_JSON;
            if (!config || config.length < 10) {
              console.error('FIREBASE_CONFIG secret is not set or is invalid!');
              process.exit(1);
            }

            // Replace the placeholder string, including the quotes around it,
            // with the actual JSON config from the secret.
            const newContent = content.replace(/'__FIREBASE_CONFIG_PLACEHOLDER__'/g, config);
            
            fs.writeFileSync(path, newContent);
            console.log('Firebase config injected successfully.');
          "

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload the entire /docs directory
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
